[package]
name = "easyjob-scheduler"
version = "1.0.2"
edition = "2021"

[dependencies]
easyjob-common = { path = "../common" }
easyjob-domain = { path = "../domain" }
chrono.workspace = true
chrono-tz.workspace = true
croner.workspace = true
rand.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
async-trait.workspace = true
